# Generated by Django 5.2.6 on 2025-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_register_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='addroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romimage', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('wifi', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('dics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
