# Generated by Django 5.2.6 on 2025-09-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_addroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addroom',
            old_name='romimage',
            new_name='roomimage',
        ),
    ]
