# Generated by Django 5.2.6 on 2025-09-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rename_romimage_addroom_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroom',
            name='roomname',
            field=models.CharField(default='Unknown Room', max_length=100),
        ),
    ]
